
CREATE TABLE public.areas (
    "id" bigint NOT NULL,
    "created_as" timestamp without time zone DEFAULT now(),
    "a" boolean DEFAULT true,
    "d" boolean DEFAULT false,
    "label" text NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "modules" text NOT NULL DEFAULT extensions.uuid_generate_v4()

);

ALTER TABLE public.areas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.areas_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.areas
    ADD CONSTRAINT areas_pkey PRIMARY KEY (id);