
CREATE TABLE public.groups (
    "id" bigint NOT NULL,
    "created_as" timestamp without time zone DEFAULT now(),
    "a" boolean DEFAULT true,
    "d" boolean DEFAULT false,
    "label" text NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "order" bigint NOT NULL DEFAULT 500

);

ALTER TABLE public.groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.groups_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.groups
    ADD CONSTRAINT groups_pkey PRIMARY KEY (id);