
CREATE TABLE public.prontuarios (
    "id" bigint NOT NULL,
    "created_as" timestamp without time zone DEFAULT now(),
    "a" boolean DEFAULT true,
    "d" boolean DEFAULT false,
    "files" text,
    "users" bigint,
    "category" bigint,
    "pacientes" bigint,
    "medicos" bigint,
    "share" text,
    "update" timestamp without time zone,
    "label" text
);

ALTER TABLE public.prontuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prontuarios_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.prontuarios
    ADD CONSTRAINT prontuarios_pkey PRIMARY KEY (id);