
CREATE TABLE public.users (
    "id" bigint NOT NULL,
    "created_at" timestamp without time zone DEFAULT now(),
    "a" boolean DEFAULT true,
    "d" boolean DEFAULT false,
    "label" text NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "password" text NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "files" text NOT NULL DEFAULT extensions.uuid_generate_v4(),
    "email" text NOT NULL DEFAULT extensions.uuid_generate_v4()
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq1
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);